image: wso2am
image_tag: "4.5.0"
zip_url: "https://github.com/wso2/product-apim/releases/download"
cert_file: "certs/cert.pem"
pkcs12_path: "certs/certificate.p12"
pkcs12_file: "certificate.p12"
truststore_file: "client-truststore.jks"
